/**
 * AXIAL LABS · Style Dictionary build configuration
 * v1.0
 *
 * Run: `npx style-dictionary build` from /tokens/
 *
 * Inputs:  /tokens/core/*.json  +  /tokens/semantic/*.json  +  /tokens/component/*.json
 * Outputs: /tokens/build/tokens.css, tokens.tailwind.js, tokens.figma.json
 *
 * Install: `npm i -D style-dictionary`
 */

const StyleDictionary = require('style-dictionary');

// --- Custom transform: rgb shadows aren't natively supported by SD, register pass-through
StyleDictionary.registerTransform({
  name: 'shadow/css',
  type: 'value',
  matcher: (token) => token.attributes && token.attributes.category === 'shadow',
  transformer: (token) => token.value,
});

// --- Custom format: Tailwind theme extension as a CommonJS module
StyleDictionary.registerFormat({
  name: 'javascript/tailwind',
  formatter: ({ dictionary }) => {
    const colors = {};
    const spacing = {};
    const fontSize = {};

    dictionary.allTokens.forEach((t) => {
      const path = t.path;
      if (path[0] === 'color') {
        // build nested color object: color.axial.black -> colors.axial.black
        let cursor = colors;
        for (let i = 1; i < path.length - 1; i++) {
          cursor[path[i]] = cursor[path[i]] || {};
          cursor = cursor[path[i]];
        }
        cursor[path[path.length - 1]] = t.value;
      }
      if (path[0] === 'spacing') {
        spacing[path[1]] = t.value;
      }
      if (path[0] === 'font' && path[1] === 'size') {
        fontSize[path[2]] = t.value;
      }
    });

    return `// Auto-generated by Style Dictionary. Do not edit by hand.
const axialTokens = ${JSON.stringify({ colors, spacing, fontSize }, null, 2)};
module.exports = axialTokens;
`;
  },
});

module.exports = {
  source: [
    'core/**/*.json',
    'semantic/**/*.json',
    'component/**/*.json',
  ],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'build/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: { outputReferences: true },
        },
      ],
    },
    tailwind: {
      transformGroup: 'js',
      buildPath: 'build/',
      files: [
        {
          destination: 'tokens.tailwind.js',
          format: 'javascript/tailwind',
        },
      ],
    },
    figma: {
      transformGroup: 'js',
      buildPath: 'build/',
      files: [
        {
          destination: 'tokens.figma.json',
          format: 'json/nested',
        },
      ],
    },
  },
};
